export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const CURRENT_USER = 'CURRENT_USER';
export const RETRIEVE_USERS = 'RETRIEVE_USERS';

export const RETRIEVE_ROLES = 'RETRIEVE_ROLES';

export const RECEIVE_DISHES_LIST = 'RECEIVE_DISHES_LIST';
export const RECEIVE_PRODUCT_BEGIN = 'RECEIVE_PRODUCT_BEGIN';
export const RECEIVE_PRODUCT_COMPLETED = 'RECEIVE_PRODUCT_COMPLETED';
export const RECEIVE_ORDERS_LIST = 'RECEIVE_ORDERS_LIST';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';

export const RETRIEVE_PURCHASED_DISHES = 'RETRIEVE_PURCHASED_DISHES';
export const DELETE_PURCHASED_DISHES = 'DELETE_PURCHASED_DISHES';
export const UPDATE_PURCHASED_DISHES = 'UPDATE_PURCHASED_DISHES';
export const CREATE_PURCHASED_DISHES = 'CREATE_PURCHASED_DISHES';

export const RETRIEVE_ORGANIZATIONS = 'RETRIEVE_ORGANIZATIONS';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
